### ISSUE TITLE
Will List be used as in EMA example implementation

### ISSUE THREAD

**Issue by jkiddo** [Gravitate-Health/focusing-manager#18]
Hi there - Will the List resource be added as a grouper function for related leaflets as specified on https://github.com/EuropeanMedicinesAgency/EU-ePI-common-standard or will it not?

**Comment by amedranogil** [comment]
hello, I would like to say yes, as we are gearing towards EMA compatibility. However, I am not sure about the technical details, maybe @joofio could help us understand a bit better the implications and the larger picture?

**Comment by jkiddo** [comment]
@amedranogil I would also need to know _when_ you intent to support it - as we used the EMA mappings for List functionality for the first prototype 1.5 years ago.

**Comment by amedranogil** [comment]
hello @jkiddo , I would like to say I would be ready as soon as possible, however I am not sure about what exactly the issue is. I mean, we have agreed to be FHIR compliant, and we are leaning towards the european approach. In technical terms I am not sure if this is just a matter of tuning the content or if we need to update the services and what this update entails. To be able to answer your question I will need to know a bit more about what are you expecting of what you propose for supporting this.

**Comment by jkiddo** [comment]
The List resource is/was used in the EMA setup to group leaflets for the same product but in different languages. I guess an easy way to do it would be for it to be added to the IG. I'll make a issue for it.

**Comment by jkiddo** [comment]
@amedranogil if we add it to the IG will you then import it into your FHIR server?

**Comment by amedranogil** [comment]
yes

**Comment by jkiddo** [comment]
@amedranogil I don't see any entries being present on https://fosps.gravitatehealth.eu/epi/api/fhir/List right now

**Comment by gmej** [comment]
Hi @jkiddo , let us update the IG in our server and we will notify you when Lists are ready.

**Comment by gmej** [comment]
@jkiddo are those resources coming from here https://build.fhir.org/ig/hl7-eu/gravitate-health/ ?

**Comment by jkiddo** [comment]
A list is now ready: http://build.fhir.org/ig/hl7-eu/gravitate-health/List-listDovato.html

**Comment by jkiddo** [comment]
I've uploaded a sample here: https://fosps.gravitatehealth.eu/epi/api/fhir/List/10617

**Comment by gmej** [comment]
It was an error in the FHIR connector, it wasn't looking for "List" resource. Now it is updated. However there is a problem with one of the lists: "List/list-grouper", It reports the following error: 
```Reason: HAPI-0505: Invalid resource reference found at path[List.entry.item] - Does not contain resource type - bundlepackageleaflet-379d610f9c96d541562699215b0864126 ```

I found that it is a non-existant id for a bundle.

**Comment by jkiddo** [comment]
Se also https://github.com/hl7-eu/gravitate-health/issues/15

**Comment by jkiddo** [comment]
> It was an error in the FHIR connector, it wasn't looking for "List" resource. Now it is updated. However there is a problem with one of the lists: "List/list-grouper", It reports the following error: `Reason: HAPI-0505: Invalid resource reference found at path[List.entry.item] - Does not contain resource type - bundlepackageleaflet-379d610f9c96d541562699215b0864126 `
> 
> I found that it is a non-existant id for a bundle.

I've fixed that now with https://github.com/hl7-eu/gravitate-health/commit/c85c719b30b0317d3c9da1c512d64e62258844e7

**Comment by jkiddo** [comment]
General discussion is now moved to https://github.com/hl7-eu/gravitate-health/issues/15
