### ISSUE TITLE
[LNS] Add example lens that adds information to the ePI

### ISSUE THREAD

**Issue by jkiddo** [Gravitate-Health/focusing-manager#31]
Can I request a lens that just adds some information to the ePI - e.g. some text or links or images - if not already done?

**Comment by aalonsolopez** [comment]
Currently working and discussing a lens that adds iconography, which is pretty the same in my opinion... Does it suits your request?

**Comment by joofio** [comment]
linked (if not duplicate) of https://github.com/Gravitate-Health/mvp-issues/issues/29 right?

**Comment by jkiddo** [comment]
Yes

**Comment by joofio** [comment]
closed and to be followed on https://github.com/Gravitate-Health/mvp-issues/issues/29
