### ISSUE TITLE
Invalid FHIR bundle returned

### ISSUE THREAD

**Issue by jkiddo** [Gravitate-Health/focusing-manager#5]
When invoking the focus manager with e.g. `https://fosps.gravitatehealth.eu/focusing/focus/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165?patientId=5ecb793d-e4e1-4aab-b734-36f6bad06b1e&lenses=lens-selector-mvp2_pregnancy` (IPS omitted for brevity) - the bundle returned is not valid FHIR for e.g. `PackagedProductDefinition`as the quantity of the pagageproductdefinition with id ppd-a223062bf3faf7acb3e6e80760fa4e91 is set to    `"quantity": 28.0,`- but quantity is typed as an integer and 28.0 is not an integer - its a decimal (https://hl7.org/fhir/packagedproductdefinition-definitions.html#PackagedProductDefinition.packaging.quantity).
[result.txt](https://github.com/Gravitate-Health/focusing-manager/files/11777293/result.txt)

**Comment by jkiddo** [comment]
You're right - there's a bug in the HAPI FHIR framework. I'll file a bug report

**Comment by aalonsolopez** [comment]
Nice. I'll assign this issue to @joofio, and if he consider to close the issue from this repo, for me it's perfect.

**Comment by jkiddo** [comment]
@joofio cannot fix this - and I've found that its not directly HAPI related. Its a class loader thing, I think.
